EloverdeTech/ng-tailwind

.gitignore, angular.json, ng-tailwind-config.js, package-lock.json, package.json, src/app/app.component.ts, src/app/pages/action-components/ngt-floating-button-page/ngt-floating-button-page.component.ts, src/app/pages/action-components/ngt-floating-button-page/ngt-floating-button-page.module.ts, src/app/pages/home/home.component.ts, src/index.html, src/tailwind.css, tailwind.config.js
* Add Tailwindcss and scripts.
=> Merge Documentation

angular.json, e2e/src/app.e2e-spec.ts, karma.conf.js, ng-tailwind-config.js, package-lock.json, package.json, projects/ng-tailwind/package-lock.json, projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-floating-button/ngt-floating-button.component.html, projects/ng-tailwind/src/components/ngt-floating-button/ngt-floating-button.component.ts, projects/ng-tailwind/src/components/ngt-sidenav/ngt-sidenav.component.html, projects/ng-tailwind/src/components/ngt-sidenav/ngt-sidenav.component.ts, src/app/app.component.spec.ts, src/app/pages/action-components/ngt-floating-button-page/ngt-floating-button-page.component.html, src/app/pages/action-components/ngt-floating-button-page/ngt-floating-button-page.component.ts, src/app/pages/home/home.component.html, src/index.html
* Update documentation -- NgtFloatingButton;
* Update ng-tailwind version -- 0.0.74;
* Update project name.
=> Merge Master -- Documentation

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-dropzone/ngt-dropzone.component.ts
Added navigation buttons on image viewer
=> Update version -- 1.1.212

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.ts
https://eloverde.atlassian.net/browse/ELO600-2357
=> [ELO600-2357] [ABORGAMA] Correções do layout da RUT (CNPJ)

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-datatable/ngt-datatable.component.ts
https://eloverde.atlassian.net/browse/ELO600-2278
=> [ELO600-2278] Plano de Ação / Não Conformidade para Documentos

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-checkbox/ngt-checkbox.component.html, projects/ng-tailwind/src/components/ngt-checkbox/ngt-checkbox.component.ts
https://eloverde.atlassian.net/browse/ELO600-2356
=> [ELO600-2356] [ABORGAMA] Parâmetro para justificar tarefas

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-dropzone/ngt-dropzone.component.ts
https://eloverde.atlassian.net/browse/ELO600-2569
=> [ELO600-2569] Erros em relação aos attachments

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-helper/ngt-helper.component.html, projects/ng-tailwind/src/components/ngt-helper/ngt-helper.component.ts
https://eloverde.atlassian.net/browse/ELO600-2012
=> [ELO600-2012] Tarefas para Documentos

projects/ng-tailwind/src/components/ngt-modal/ngt-modal-header/ngt-modal-header.component.html, projects/ng-tailwind/src/components/ngt-modal/ngt-modal-header/ngt-modal-header.component.ts, projects/ng-tailwind/src/components/ngt-modal/ngt-modal.component.html, projects/ng-tailwind/src/components/ngt-modal/ngt-modal.component.ts
https://eloverde.atlassian.net/browse/ELO600-2986
=> [ELO600-2986] Situações de layout encontradas no módulo do transportador

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-dropdown/ngt-dropdown.component.html, projects/ng-tailwind/src/components/ngt-dropdown/ngt-dropdown.component.ts
https://eloverde.atlassian.net/browse/ELO600-1023
=> [ELO600-1023] [HOTFIX] Posicionamento do dropdown

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-date/ngt-date.component.html, projects/ng-tailwind/src/components/ngt-date/ngt-date.component.ts, projects/ng-tailwind/src/components/ngt-helper/ngt-helper.component.html, projects/ng-tailwind/src/components/ngt-helper/ngt-helper.component.ts, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.html, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.ts, projects/ng-tailwind/src/components/ngt-select/ngt-select.component.html, projects/ng-tailwind/src/components/ngt-select/ngt-select.component.ts
https://eloverde.atlassian.net/browse/ELO600-3130
=> [ELO600-3130] [VEOLIA] Correção dos helpers da plataforma

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-dropzone/ngt-dropzone.component.html, projects/ng-tailwind/src/components/ngt-dropzone/ngt-dropzone.component.ts
https://eloverde.atlassian.net/browse/ELO600-3047
=> [ELO600-3047] [SOLVÍ] Incluir preview dos anexos dos comentários

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.ts
https://eloverde.atlassian.net/browse/ELO600-3443
=> [ELO600-3443] [VEOLIA] Aumentar quantidade de caracteres na descrição dos itens do plano de ação

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.html, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.ts, projects/ng-tailwind/src/components/ngt-validation/ngt-validation.component.html, projects/ng-tailwind/src/services/http/ngt-http-validation.service.ts, projects/ng-tailwind/src/services/http/ngt-translate.service.ts, src/app/services/ngt-translate-default.service.ts
https://eloverde.atlassian.net/browse/ELO600-3275
=> [ELO600-3275] Política de Senha para o Grupo Empresarial

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-popover/ngt-popover-tooltip/ngt-popover-tooltip.component.ts, projects/ng-tailwind/src/components/ngt-popover/ngt-popover.directive.ts
https://eloverde.atlassian.net/browse/ELO600-3471
=> [ELO600-3471] Erro na hora de mostrar erro na movimentação de resíduos

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-slider/ngt-slider.component.html, projects/ng-tailwind/src/components/ngt-slider/ngt-slider.component.ts
https://eloverde.atlassian.net/browse/ELO600-3575
=> [ELO600-3575] [VEOLIA] Novos tipos de campos para checklists

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-select/ngt-select.component.ts
https://eloverde.atlassian.net/browse/ELO600-3577
=> [ELO600-3577]  [VEOLIA] Solicitação de checklist para parceiros conectados

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.ts
https://eloverde.atlassian.net/browse/ELO600-3832
=> [ELO600-3821]Ajustar os placeholder que somem ao clicar nos campos

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-checkbox/ngt-checkbox.component.ts, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.ts, projects/ng-tailwind/src/components/ngt-select/ngt-select.component.ts
https://eloverde.atlassian.net/browse/ELO600-3831
=> [ELO600-3831] Corrigir visualização e ajustar descrição dos textos de ajuda da plataforma

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-action/ngt-action.component.ts, projects/ng-tailwind/src/components/ngt-button/ngt-button.component.html, projects/ng-tailwind/src/components/ngt-button/ngt-button.component.ts, projects/ng-tailwind/src/components/ngt-checkbox/ngt-checkbox.component.html, projects/ng-tailwind/src/components/ngt-checkbox/ngt-checkbox.component.ts, projects/ng-tailwind/src/components/ngt-datatable/ngt-datatable.component.ts, projects/ng-tailwind/src/components/ngt-form/ngt-form.component.html, projects/ng-tailwind/src/components/ngt-form/ngt-form.component.ts, projects/ng-tailwind/src/components/ngt-radio-button/ngt-radio-button.component.html, projects/ng-tailwind/src/components/ngt-radio-button/ngt-radio-button.component.ts, projects/ng-tailwind/src/components/ngt-section/ngt-section.component.html, projects/ng-tailwind/src/components/ngt-section/ngt-section.component.ts, projects/ng-tailwind/src/components/ngt-select/ngt-select.component.html, projects/ng-tailwind/src/components/ngt-select/ngt-select.component.ts, projects/ng-tailwind/src/components/ngt-shining/ngt-shining.component.css
* **feat:** disable components when NgtForm or NgtSection are disabled;
* **fix:** CSS animation of NgtShining.
=> Version 4.3.30

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-multi-select/ngt-multi-select.component.html, projects/ng-tailwind/src/components/ngt-multi-select/ngt-multi-select.component.ts
https://eloverde.atlassian.net/browse/ELO600-3806
=> [ELO600-3831][DEXCO] Erro ao selecionar as atividades no aplicativo

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-shining/ngt-shining.component.css
fix: setting axis on ngt-multi-select helper
=> Version 4.3.31

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-button/ngt-button.component.html, projects/ng-tailwind/src/components/ngt-multi-select/ngt-multi-select.component.html
https://eloverde.atlassian.net/browse/ELO600-3950
=> [ELO600-3950] Melhorias importação de MTR

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-select/ngt-select.component.html, projects/ng-tailwind/src/components/ngt-select/ngt-select.component.ts
https://eloverde.atlassian.net/browse/ELO600-3982
=> [ELO600-3982] [Perfis Personalizados] Vinculo de Widgets a Perfis

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-select/ngt-select.component.ts
https://eloverde.atlassian.net/browse/ELO600-3767
=> [ELO600-3767] [Perfis Personalizados] Bloqueio de Requisições pela API

projects/ng-tailwind/src/components/ngt-input/ngt-input.component.html, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.ts, projects/ng-tailwind/src/helpers/input-mask/input-mask.helper.ts
https://eloverde.atlassian.net/browse/ELO200-472
=> [ELO200-472] [DASA] Permitir cadastrar empresas, parceiros e empreendimentos com o CNPJ (CUIT) da argentina

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-radio-button/ngt-radio-button.component.html
https://eloverde.atlassian.net/browse/ELO600-4122
=> [ELO600-4122] [VEOLIA] Nota - Ajustar variáveis de avaliação numérica no checklist

projects/ng-tailwind/src/components/ngt-button/ngt-button.component.html, projects/ng-tailwind/src/components/ngt-button/ngt-button.component.ts
https://eloverde.atlassian.net/browse/ELO600-4207
=> [ELO600-4207]Melhorar visualização dos manuais na plataforma 

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.ts, projects/ng-tailwind/src/components/ngt-validation/ngt-validation.component.html, projects/ng-tailwind/src/services/http/ngt-translate.service.ts, src/app/services/ngt-translate-default.service.ts
https://eloverde.atlassian.net/browse/ELO200-778
=> [ELO200-778] Alteração de senha na plataforma e recuperação de senhas

projects/ng-tailwind/src/components/ngt-dropzone/ngt-dropzone-file-viewer/ngt-dropzone-file-viewer.component.ts
https://eloverde.atlassian.net/browse/ELO200-776
=> [ELO200-776] [HOTFIX][VEOLIA] Não é possível visualizar anexos incluídos nas auditorias por serem muito grande

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-textarea/ngt-textarea.component.html
https://eloverde.atlassian.net/browse/ELO600-4426
=> [ELO600-4426] [VEOLIA] Erros encontrados na validação do checklist pelo cliente

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-slider/ngt-slider.component.html, projects/ng-tailwind/src/components/ngt-slider/ngt-slider.component.ts
The manual update of the value was removed because when a component was using more than one instance, the value didn't update
=> fix(NgtSlider): removed manual update of value on html

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-datatable/ngt-datatable.component.html, projects/ng-tailwind/src/components/ngt-datatable/ngt-datatable.component.ts, projects/ng-tailwind/src/components/ngt-datatable/ngt-th-check/ngt-th-check.component.ts
https://eloverde.atlassian.net/browse/ELO201-560
=> [ELO201-560] Melhorias na geração de CDF

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-dropzone/ngt-dropzone-file-viewer/ngt-dropzone-file-viewer.component.ts
https://eloverde.atlassian.net/browse/ELO201-1832
=> fix (NgtDropzoneFileViewer): Add timeout with 10 seconds to hide loading

projects/ng-tailwind/package.json, projects/ng-tailwind/src/components/ngt-date/ngt-date.component.html, projects/ng-tailwind/src/components/ngt-input/ngt-input.component.html, projects/ng-tailwind/src/components/ngt-multi-select/ngt-multi-select.component.html, projects/ng-tailwind/src/components/ngt-select/ngt-select.component.html, projects/ng-tailwind/src/components/ngt-textarea/ngt-textarea.component.html
https://eloverde.atlassian.net/browse/ELO600-4117
=> [ELO600-4117] [NgTailwind] Ajuste na label dos campos
